-- Vortex Admin new tables (bundles + scheduled CP)
-- Target DB: comp_hack (MariaDB/MySQL)
--
-- Safe to run multiple times: uses IF NOT EXISTS guards.
--
-- Note:
-- - IDs are stored as CHAR(36) UUID strings generated by the application (TypeORM).
-- - JSON fields use TEXT to stay compatible across MariaDB versions; TypeORM's `simple-json`
--   serializes/deserializes automatically.

CREATE TABLE IF NOT EXISTS `vtx_item_bundles` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `cpCost` INT NOT NULL DEFAULT 0,
  `products` TEXT NOT NULL,
  `createdByUsername` VARCHAR(32) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_vtx_item_bundles_name` (`name`),
  KEY `IDX_vtx_item_bundles_createdByUsername` (`createdByUsername`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vtx_item_bundle_send_batches` (
  `id` CHAR(36) NOT NULL,
  `bundleId` CHAR(36) NOT NULL,
  `bundleName` VARCHAR(64) NOT NULL,
  `cpCost` INT NOT NULL DEFAULT 0,
  `products` TEXT NOT NULL,
  `reason` VARCHAR(140) NULL,
  `createdByUsername` VARCHAR(32) NOT NULL,
  `status` ENUM('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `scheduledAt` DATETIME(3) NOT NULL,
  `completedAt` DATETIME(3) NULL,
  `totalRecipients` INT NOT NULL DEFAULT 0,
  `processedCount` INT NOT NULL DEFAULT 0,
  `successCount` INT NOT NULL DEFAULT 0,
  `failureCount` INT NOT NULL DEFAULT 0,
  `lastError` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `IDX_vtx_item_bundle_send_batches_bundleId` (`bundleId`),
  KEY `IDX_vtx_item_bundle_send_batches_createdByUsername` (`createdByUsername`),
  KEY `IDX_vtx_item_bundle_send_batches_status` (`status`),
  KEY `IDX_vtx_item_bundle_send_batches_scheduledAt` (`scheduledAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vtx_item_bundle_send_recipients` (
  `id` CHAR(36) NOT NULL,
  `batchId` CHAR(36) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `status` ENUM('PENDING','SENT','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `attempts` INT NOT NULL DEFAULT 0,
  `lastError` TEXT NULL,
  `sentAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `IDX_vtx_item_bundle_send_recipients_batchId` (`batchId`),
  KEY `IDX_vtx_item_bundle_send_recipients_username` (`username`),
  KEY `IDX_vtx_item_bundle_send_recipients_status` (`status`),
  CONSTRAINT `FK_vtx_item_bundle_send_recipients_batchId`
    FOREIGN KEY (`batchId`) REFERENCES `vtx_item_bundle_send_batches` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vtx_scheduled_cp_grants` (
  `id` CHAR(36) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `amount` INT NOT NULL,
  `reason` VARCHAR(140) NULL,
  `createdByUsername` VARCHAR(32) NOT NULL,
  `status` ENUM('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `scheduledAt` DATETIME(3) NOT NULL,
  `processedAt` DATETIME(3) NULL,
  `previousCp` INT NULL,
  `newCp` INT NULL,
  `attempts` INT NOT NULL DEFAULT 0,
  `lastError` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `IDX_vtx_scheduled_cp_grants_username` (`username`),
  KEY `IDX_vtx_scheduled_cp_grants_createdByUsername` (`createdByUsername`),
  KEY `IDX_vtx_scheduled_cp_grants_status` (`status`),
  KEY `IDX_vtx_scheduled_cp_grants_scheduledAt` (`scheduledAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

